"""Vzfg Q3: out-of-distribution rollout for the GNN and the Known-ODE.

The claim under test is that fitting activity is not the same as recovering
mechanism. In distribution every model rolls out well, so the test has to move
off the data manifold. We vary only the drive I_i(t), keep the checkpoints
frozen, and compare each model's autoregressive rollout against ground truth
generated by the true ODE under the same drive.

Conditions
    id       naturalistic held-out video (in-distribution reference)
    white    full-field white noise: one time series, broadcast to every
             photoreceptor, matched to the naturalistic drive SD. Spatially
             uniform, temporally unstructured -- the opposite of natural video.
    inject   naturalistic drive plus a constant current into a random 5% of
             ALL neurons, including neurons no visual stimulus can reach.

Drifting gratings are not included: they need the retinal hex lattice, which
lives in the Flyvis stimulus renderer rather than in ode_params.

Ground truth integrates Eq. 1 deterministically (no process noise), so the
comparison is not limited by irreducible noise:
    v <- v + dt * (-v + V_rest + W ReLU(v) + I) / tau

Usage
-----
    GNN_OUTPUT_ROOT=/groups/.../GraphData PYTHONPATH=src \
      python figures/flyvis/fig_ood_rollout.py [--n-steps 1000]

Output
------
    figures/flyvis/results_ood_rollout.json
"""
import argparse
import json
import os
import sys

import numpy as np
import torch

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(REPO, 'src'))

import importlib.util                                                   # noqa: E402
_spec = importlib.util.spec_from_file_location(
    'jac', os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        'fig_jacobian_gnn_knownode.py'))
jac = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(jac)                    # reuse load_run / _t / NeuronState

from connectome_gnn.neuron_state import NeuronState                     # noqa: E402
from connectome_gnn.utils import set_data_root, to_numpy                # noqa: E402

GNN_CFG = 'flyvis_noise_005_blank50_unified_cv00'
ODE_CFG = 'flyvis_noise_005_blank50_known_ode_cv00'
DT = 0.02
SEED = 0


def true_dvdt(v, stim, W_dense, tau, vrest):
    """Eq. 1, evaluated densely: (-v + V_rest + W ReLU(v) + I) / tau."""
    return (-v + vrest + W_dense @ torch.relu(v) + stim) / tau


def rollout_true(v0, stim_seq, W_dense, tau, vrest):
    v = v0.clone(); out = []
    for t in range(stim_seq.shape[0]):
        v = v + DT * true_dvdt(v, stim_seq[t], W_dense, tau, vrest)
        out.append(v.clone())
    return torch.stack(out)


def rollout_model(model, v0, stim_seq, edge_index, device):
    """Autoregressive rollout; the model supplies dv/dt each step."""
    n = v0.shape[0]
    idx = torch.arange(n, device=device)
    data_id = torch.zeros(n, dtype=torch.long, device=device)
    v = v0.clone(); out = []
    with torch.no_grad():
        for t in range(stim_seq.shape[0]):
            state = NeuronState(voltage=v, stimulus=stim_seq[t], index=idx)
            dv = model(state, edge_index, data_id=data_id, k=t).squeeze(-1)
            v = v + DT * dv
            out.append(v.clone())
    return torch.stack(out)


def pearson(a, b):
    a = to_numpy(a).ravel(); b = to_numpy(b).ravel()
    m = np.isfinite(a) & np.isfinite(b)
    if m.sum() < 2 or a[m].std() == 0 or b[m].std() == 0:
        return float('nan')
    return float(np.corrcoef(a[m], b[m])[0, 1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--n-steps', type=int, default=1000)
    ap.add_argument('--inject-frac', type=float, default=0.05)
    ap.add_argument('--inject-sd', type=float, default=1.0,
                    help='injected current in units of the visual-drive SD')
    ap.add_argument('--device', default='cuda' if torch.cuda.is_available() else 'cpu')
    args = ap.parse_args()

    set_data_root(os.environ.get('GNN_OUTPUT_ROOT',
                                 '/groups/saalfeld/home/allierc/GraphData'))
    dev = torch.device(args.device)
    print(f'device={dev}  n_steps={args.n_steps}')

    print('loading runs ...')
    _, gnn, odep, gdata = jac.load_run(GNN_CFG, dev)
    _, ode_model, _, _ = jac.load_run(ODE_CFG, dev)

    edge_index = odep.edge_index.to(dev)
    n = int(edge_index.max()) + 1
    W = jac._t(odep.W, dev).squeeze()
    tau = jac._t(odep.tau_i, dev).squeeze()
    vrest = jac._t(odep.V_i_rest, dev).squeeze()
    W_dense = torch.zeros((n, n), device=dev)
    W_dense[edge_index[1], edge_index[0]] = W          # row = postsyn, col = presyn

    volt, stim, _ = jac.sample_frames(gdata, args.n_steps + 1, dev)
    volt, stim = volt[:args.n_steps + 1], stim[:args.n_steps + 1]
    v0 = volt[0].to(dev)
    stim_id = stim[:args.n_steps].to(dev)

    retinal = (stim_id.abs().sum(0) > 0)
    print(f'  N={n}  driven neurons={int(retinal.sum())}  steps={args.n_steps}')

    rng = np.random.default_rng(SEED)
    g = torch.Generator(device='cpu').manual_seed(SEED)

    # full-field white noise: one time series shared by every photoreceptor
    sd = stim_id[:, retinal].std()
    ff = torch.randn(args.n_steps, 1, generator=g).to(dev) * sd
    stim_white = torch.zeros_like(stim_id)
    stim_white[:, retinal] = ff

    # current injection into a random 5% of ALL neurons
    k = max(1, int(args.inject_frac * n))
    tgt = torch.as_tensor(rng.choice(n, size=k, replace=False), device=dev)
    stim_inj = stim_id.clone()
    stim_inj[:, tgt] += args.inject_sd * sd

    conditions = {'id': stim_id, 'white': stim_white, 'inject': stim_inj}
    out = {'n_steps': args.n_steps, 'n_neurons': n, 'dt': DT,
           'gnn_config': GNN_CFG, 'known_ode_config': ODE_CFG,
           'inject_frac': args.inject_frac, 'n_injected': int(k),
           'inject_sd': args.inject_sd,
           'conditions': {}}

    for name, ss in conditions.items():
        gt = rollout_true(v0, ss, W_dense, tau, vrest)
        r_gnn = pearson(rollout_model(gnn, v0, ss, edge_index, dev), gt)
        r_ode = pearson(rollout_model(ode_model, v0, ss, edge_index, dev), gt)
        out['conditions'][name] = {'gnn_rollout_r': r_gnn,
                                   'known_ode_rollout_r': r_ode}
        print(f'  {name:<8} GNN r={r_gnn:.4f}   Known-ODE r={r_ode:.4f}')

    dst = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                       'results_ood_rollout.json')
    with open(dst, 'w') as f:
        json.dump(out, f, indent=2)
    print(f'\nwrote {dst}')


if __name__ == '__main__':
    main()
