"""Poster figure: 50%-ablation rollout, single-row interleaved layout.

Poster variant of ``fig_rollout_3col_noise_comparison_ablation50.py`` (nf_green
case). Instead of the paper's two-row grid (traces row over scatters row), each
noise column is laid out as a [trace strip | scatter] pair, and the three
columns sit side-by-side in a single row -- matching the existing
poster_fig_rollout_ablation50_nf_green.pdf. Fonts are enlarged for the poster
and an SVG is written alongside the pdf/png.

Reuses the data loading and drawing helpers from the paper module (imported),
so nothing about the underlying rollout/metrics changes; only the layout and
font sizes differ.

Usage
-----
    conda run -n neural-graph-linux \\
        python figures/flyvis/poster_fig_rollout_ablation50_nf_green.py

Output
------
    figures/flyvis/poster/poster_fig_rollout_ablation50_nf_green.{pdf,png,svg}
"""

import os
import sys

import matplotlib
matplotlib.use('Agg')

import matplotlib.gridspec as mgs
import matplotlib.pyplot as plt
import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _HERE)

# Import the paper module (sets the janne matplotlibrc on import) and reuse its
# COLUMNS / loaders / drawing helpers.
import fig_rollout_3col_noise_comparison_ablation50 as R  # noqa: E402

# ── enlarge fonts for the poster (matches poster_fig_training_traces_3_col) ──
R.FS_LABEL = 15
R.FS_TICK  = 12
R.FS_ANNOT = 11
R.FS_TYPE  = 10
FS_TITLE   = 16

# Single-row figure: wide and short.
FIG_W_IN = 20.0
FIG_H_IN = 3.4
# Per noise column: trace strip wider than the square scatter.
GROUP_WIDTH_RATIOS = [1.7, 1.0]
# Extra left-shift for the "neurons" y-label so it clears the type names.
YLABEL_PAD = 34


def main():
    cols = R.COLUMNS

    # Bundles already exist on disk (generated by the paper script); just load.
    matched = [R.load_matched_bundle(c) for c in cols]
    nf      = [R.load_nf_bundle(c)      for c in cols]
    trace_src = matched

    # Neuron selection from the first column's type ids.
    type_ids   = trace_src[0]['type_ids']
    type_names = trace_src[0]['type_names']
    index_to_name = {i: type_names[i] for i in range(len(type_names))}
    neuron_idx, labels = [], []
    for t in R.SELECTED_TYPES:
        ids = np.where(type_ids == t)[0]
        if len(ids) > 0:
            neuron_idx.append(int(ids[0]))
            labels.append(index_to_name.get(t, f'Type{t}'))

    step_vs = [3.0 * R.TRACE_SHRINK * float(np.std(R._slice(ts['true'], neuron_idx)))
               for ts in trace_src]
    step_v = max(0.5 * R.TRACE_SHRINK, max(step_vs))
    n_frames = R.TRACE_END - R.TRACE_START
    time_ms = np.arange(n_frames) * R.DT_MS + R.TRACE_START * R.DT_MS

    from connectome_gnn.utils import compute_trace_metrics, fisher_pool

    fig = plt.figure(figsize=(FIG_W_IN, FIG_H_IN), constrained_layout=False)
    outer = mgs.GridSpec(
        1, 3, figure=fig,
        left=0.05, right=0.995, top=0.86, bottom=0.17,
        wspace=0.05,
    )

    trace_axes = []
    for c, (col, ts, n) in enumerate(zip(cols, trace_src, nf)):
        inner = mgs.GridSpecFromSubplotSpec(
            1, 2, outer[0, c],
            width_ratios=GROUP_WIDTH_RATIOS, wspace=0.30,
        )
        ax_tr = fig.add_subplot(inner[0, 0])
        ax_sc = fig.add_subplot(inner[0, 1])

        # nf_green: ground-truth traces are always the noise-free ablated GT.
        true_w = R._slice(trace_src[0]['true'], neuron_idx)
        pred_w = R._slice(ts['pred'], neuron_idx)
        # Poster: omit the red stimulus trace.
        stim_w = None

        # r vs noise-free ablated GT (matches the paper recipe).
        _src = n if col['noise_level'] > 0 else ts
        _, _pear, _, _ = compute_trace_metrics(
            np.asarray(_src['true']), np.asarray(_src['pred']))
        _fp = fisher_pool(_pear)
        r_nf, r_sd_nf = float(_fp['r_mean']), float(_fp['r_sd_sym'])
        header = f"$r$ = {r_nf:.2f} $\\pm$ {r_sd_nf:.2f}"

        R.draw_traces(
            ax_tr, true_w, pred_w, stim_w, labels, step_v, time_ms,
            column_title=f"{col['label']} ({col['sigma']})",
            show_type_labels=(c == 0),
            show_xlabel=True,
            header_text=header,
            apply_affine=False,
        )
        # Shift the "neurons" y-label further left, clear of the type names.
        if c == 0:
            ax_tr.set_ylabel('neurons', fontsize=R.FS_LABEL, labelpad=YLABEL_PAD)

        # scatter: rollout vs noise-free ablated GT; axis labels on first only.
        R.draw_scatter(
            ax_sc, nf[c]['true'], nf[c]['pred'],
            xlabel=('ground truth voltage' if c == 0 else ''),
            ylabel=('rollout voltage' if c == 0 else ''),
            show_fit=True, show_r=True,
        )
        trace_axes.append(ax_tr)

    # Column titles centered over each trace+scatter group.
    fig.canvas.draw()
    for c, ax_t in enumerate(trace_axes):
        pos_tr = ax_t.get_position()
        # center over the whole group (trace left edge to figure slot).
        x_center = pos_tr.x0 + pos_tr.width * 0.62
        fig.text(x_center, 0.93, ax_t._column_title,
                 va='bottom', ha='center', fontsize=FS_TITLE,
                 fontweight='normal', transform=fig.transFigure)

    out_dir = os.path.join(_HERE, 'poster')
    out_base = os.path.join(out_dir, 'poster_fig_rollout_ablation50_nf_green')
    fig.savefig(out_base + '.pdf', bbox_inches='tight')
    fig.savefig(out_base + '.png', dpi=600, bbox_inches='tight')
    fig.savefig(out_base + '.svg', bbox_inches='tight')
    plt.close(fig)
    print(f'wrote {out_base}.{{pdf,png,svg}}')


if __name__ == '__main__':
    main()
